package com.gpachov.adf.foodrepo.model;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jun 12 23:51:06 EEST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FoodAppModelImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public FoodAppModelImpl() {
    }

    /**
     * Container's getter for ProductEntriesView2.
     * @return ProductEntriesView2
     */
    public ViewObjectImpl getProductEntriesView2() {
        return (ViewObjectImpl) findViewObject("ProductEntriesView2");
    }

    /**
     * Container's getter for RecipesView.
     * @return RecipesView
     */
    public ViewObjectImpl getRecipesView() {
        return (ViewObjectImpl) findViewObject("RecipesView");
    }

    /**
     * Container's getter for AppFoodModule.
     * @return AppFoodModule
     */
    public ApplicationModuleImpl getAppFoodModule() {
        return (ApplicationModuleImpl) findApplicationModule("AppFoodModule");
    }
}

