package com.gpachov.adf.foodrepo.model;

import oracle.jbo.server.EntityCache;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jun 11 01:35:34 EEST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RecipeCollImpl extends EntityCache {
    /**
     * This is the default constructor (do not remove).
     */
    public RecipeCollImpl() {
    }
}

